// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsprofile.proto

package bfd.newsprofile;

public final class Newsprofile {
  private Newsprofile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewsProfileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string cid = 1;
    boolean hasCid();
    String getCid();
    
    // required string iid = 2;
    boolean hasIid();
    String getIid();
    
    // required string url = 3;
    boolean hasUrl();
    String getUrl();
    
    // required string bfdiid = 4;
    boolean hasBfdiid();
    String getBfdiid();
    
    // optional string bfd_cat = 5;
    boolean hasBfdCat();
    String getBfdCat();
    
    // optional string bfd_tag = 6;
    boolean hasBfdTag();
    String getBfdTag();
    
    // repeated string bfd_cat_vec = 7;
    java.util.List<String> getBfdCatVecList();
    int getBfdCatVecCount();
    String getBfdCatVec(int index);
    
    // repeated string bfd_tag_vec = 8;
    java.util.List<String> getBfdTagVecList();
    int getBfdTagVecCount();
    String getBfdTagVec(int index);
    
    // optional string loc = 9;
    boolean hasLoc();
    String getLoc();
  }
  public static final class NewsProfile extends
      com.google.protobuf.GeneratedMessage
      implements NewsProfileOrBuilder {
    // Use NewsProfile.newBuilder() to construct.
    private NewsProfile(Builder builder) {
      super(builder);
    }
    private NewsProfile(boolean noInit) {}
    
    private static final NewsProfile defaultInstance;
    public static NewsProfile getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewsProfile getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bfd.newsprofile.Newsprofile.internal_static_bfd_newsprofile_NewsProfile_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bfd.newsprofile.Newsprofile.internal_static_bfd_newsprofile_NewsProfile_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string cid = 1;
    public static final int CID_FIELD_NUMBER = 1;
    private java.lang.Object cid_;
    public boolean hasCid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCid() {
      java.lang.Object ref = cid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          cid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCidBytes() {
      java.lang.Object ref = cid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        cid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string iid = 2;
    public static final int IID_FIELD_NUMBER = 2;
    private java.lang.Object iid_;
    public boolean hasIid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getIid() {
      java.lang.Object ref = iid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          iid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIidBytes() {
      java.lang.Object ref = iid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        iid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string url = 3;
    public static final int URL_FIELD_NUMBER = 3;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string bfdiid = 4;
    public static final int BFDIID_FIELD_NUMBER = 4;
    private java.lang.Object bfdiid_;
    public boolean hasBfdiid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getBfdiid() {
      java.lang.Object ref = bfdiid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          bfdiid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBfdiidBytes() {
      java.lang.Object ref = bfdiid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        bfdiid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string bfd_cat = 5;
    public static final int BFD_CAT_FIELD_NUMBER = 5;
    private java.lang.Object bfdCat_;
    public boolean hasBfdCat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getBfdCat() {
      java.lang.Object ref = bfdCat_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          bfdCat_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBfdCatBytes() {
      java.lang.Object ref = bfdCat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        bfdCat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string bfd_tag = 6;
    public static final int BFD_TAG_FIELD_NUMBER = 6;
    private java.lang.Object bfdTag_;
    public boolean hasBfdTag() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getBfdTag() {
      java.lang.Object ref = bfdTag_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          bfdTag_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBfdTagBytes() {
      java.lang.Object ref = bfdTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        bfdTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string bfd_cat_vec = 7;
    public static final int BFD_CAT_VEC_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList bfdCatVec_;
    public java.util.List<String>
        getBfdCatVecList() {
      return bfdCatVec_;
    }
    public int getBfdCatVecCount() {
      return bfdCatVec_.size();
    }
    public String getBfdCatVec(int index) {
      return bfdCatVec_.get(index);
    }
    
    // repeated string bfd_tag_vec = 8;
    public static final int BFD_TAG_VEC_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList bfdTagVec_;
    public java.util.List<String>
        getBfdTagVecList() {
      return bfdTagVec_;
    }
    public int getBfdTagVecCount() {
      return bfdTagVec_.size();
    }
    public String getBfdTagVec(int index) {
      return bfdTagVec_.get(index);
    }
    
    // optional string loc = 9;
    public static final int LOC_FIELD_NUMBER = 9;
    private java.lang.Object loc_;
    public boolean hasLoc() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getLoc() {
      java.lang.Object ref = loc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          loc_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocBytes() {
      java.lang.Object ref = loc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        loc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      cid_ = "";
      iid_ = "";
      url_ = "";
      bfdiid_ = "";
      bfdCat_ = "";
      bfdTag_ = "";
      bfdCatVec_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bfdTagVec_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      loc_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBfdiid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getBfdiidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getBfdCatBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getBfdTagBytes());
      }
      for (int i = 0; i < bfdCatVec_.size(); i++) {
        output.writeBytes(7, bfdCatVec_.getByteString(i));
      }
      for (int i = 0; i < bfdTagVec_.size(); i++) {
        output.writeBytes(8, bfdTagVec_.getByteString(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(9, getLocBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getBfdiidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getBfdCatBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getBfdTagBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < bfdCatVec_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(bfdCatVec_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getBfdCatVecList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < bfdTagVec_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(bfdTagVec_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getBfdTagVecList().size();
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getLocBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static bfd.newsprofile.Newsprofile.NewsProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bfd.newsprofile.Newsprofile.NewsProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bfd.newsprofile.Newsprofile.NewsProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bfd.newsprofile.Newsprofile.NewsProfile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bfd.newsprofile.Newsprofile.NewsProfile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bfd.newsprofile.Newsprofile.NewsProfile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bfd.newsprofile.Newsprofile.NewsProfile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static bfd.newsprofile.Newsprofile.NewsProfile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static bfd.newsprofile.Newsprofile.NewsProfile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bfd.newsprofile.Newsprofile.NewsProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(bfd.newsprofile.Newsprofile.NewsProfile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements bfd.newsprofile.Newsprofile.NewsProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bfd.newsprofile.Newsprofile.internal_static_bfd_newsprofile_NewsProfile_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bfd.newsprofile.Newsprofile.internal_static_bfd_newsprofile_NewsProfile_fieldAccessorTable;
      }
      
      // Construct using bfd.newsprofile.Newsprofile.NewsProfile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        cid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        iid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        bfdiid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        bfdCat_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        bfdTag_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        bfdCatVec_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        bfdTagVec_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        loc_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bfd.newsprofile.Newsprofile.NewsProfile.getDescriptor();
      }
      
      public bfd.newsprofile.Newsprofile.NewsProfile getDefaultInstanceForType() {
        return bfd.newsprofile.Newsprofile.NewsProfile.getDefaultInstance();
      }
      
      public bfd.newsprofile.Newsprofile.NewsProfile build() {
        bfd.newsprofile.Newsprofile.NewsProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private bfd.newsprofile.Newsprofile.NewsProfile buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        bfd.newsprofile.Newsprofile.NewsProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public bfd.newsprofile.Newsprofile.NewsProfile buildPartial() {
        bfd.newsprofile.Newsprofile.NewsProfile result = new bfd.newsprofile.Newsprofile.NewsProfile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cid_ = cid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.iid_ = iid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bfdiid_ = bfdiid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bfdCat_ = bfdCat_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bfdTag_ = bfdTag_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          bfdCatVec_ = new com.google.protobuf.UnmodifiableLazyStringList(
              bfdCatVec_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.bfdCatVec_ = bfdCatVec_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          bfdTagVec_ = new com.google.protobuf.UnmodifiableLazyStringList(
              bfdTagVec_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.bfdTagVec_ = bfdTagVec_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000040;
        }
        result.loc_ = loc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bfd.newsprofile.Newsprofile.NewsProfile) {
          return mergeFrom((bfd.newsprofile.Newsprofile.NewsProfile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(bfd.newsprofile.Newsprofile.NewsProfile other) {
        if (other == bfd.newsprofile.Newsprofile.NewsProfile.getDefaultInstance()) return this;
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasIid()) {
          setIid(other.getIid());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasBfdiid()) {
          setBfdiid(other.getBfdiid());
        }
        if (other.hasBfdCat()) {
          setBfdCat(other.getBfdCat());
        }
        if (other.hasBfdTag()) {
          setBfdTag(other.getBfdTag());
        }
        if (!other.bfdCatVec_.isEmpty()) {
          if (bfdCatVec_.isEmpty()) {
            bfdCatVec_ = other.bfdCatVec_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureBfdCatVecIsMutable();
            bfdCatVec_.addAll(other.bfdCatVec_);
          }
          onChanged();
        }
        if (!other.bfdTagVec_.isEmpty()) {
          if (bfdTagVec_.isEmpty()) {
            bfdTagVec_ = other.bfdTagVec_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureBfdTagVecIsMutable();
            bfdTagVec_.addAll(other.bfdTagVec_);
          }
          onChanged();
        }
        if (other.hasLoc()) {
          setLoc(other.getLoc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCid()) {
          
          return false;
        }
        if (!hasIid()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasBfdiid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              cid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              iid_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              url_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              bfdiid_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              bfdCat_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              bfdTag_ = input.readBytes();
              break;
            }
            case 58: {
              ensureBfdCatVecIsMutable();
              bfdCatVec_.add(input.readBytes());
              break;
            }
            case 66: {
              ensureBfdTagVecIsMutable();
              bfdTagVec_.add(input.readBytes());
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              loc_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string cid = 1;
      private java.lang.Object cid_ = "";
      public boolean hasCid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCid() {
        java.lang.Object ref = cid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          cid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cid_ = value;
        onChanged();
        return this;
      }
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = getDefaultInstance().getCid();
        onChanged();
        return this;
      }
      void setCid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        cid_ = value;
        onChanged();
      }
      
      // required string iid = 2;
      private java.lang.Object iid_ = "";
      public boolean hasIid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getIid() {
        java.lang.Object ref = iid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          iid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        iid_ = value;
        onChanged();
        return this;
      }
      public Builder clearIid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        iid_ = getDefaultInstance().getIid();
        onChanged();
        return this;
      }
      void setIid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        iid_ = value;
        onChanged();
      }
      
      // required string url = 3;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
      }
      
      // required string bfdiid = 4;
      private java.lang.Object bfdiid_ = "";
      public boolean hasBfdiid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getBfdiid() {
        java.lang.Object ref = bfdiid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          bfdiid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBfdiid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bfdiid_ = value;
        onChanged();
        return this;
      }
      public Builder clearBfdiid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bfdiid_ = getDefaultInstance().getBfdiid();
        onChanged();
        return this;
      }
      void setBfdiid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        bfdiid_ = value;
        onChanged();
      }
      
      // optional string bfd_cat = 5;
      private java.lang.Object bfdCat_ = "";
      public boolean hasBfdCat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getBfdCat() {
        java.lang.Object ref = bfdCat_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          bfdCat_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBfdCat(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bfdCat_ = value;
        onChanged();
        return this;
      }
      public Builder clearBfdCat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bfdCat_ = getDefaultInstance().getBfdCat();
        onChanged();
        return this;
      }
      void setBfdCat(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        bfdCat_ = value;
        onChanged();
      }
      
      // optional string bfd_tag = 6;
      private java.lang.Object bfdTag_ = "";
      public boolean hasBfdTag() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getBfdTag() {
        java.lang.Object ref = bfdTag_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          bfdTag_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBfdTag(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        bfdTag_ = value;
        onChanged();
        return this;
      }
      public Builder clearBfdTag() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bfdTag_ = getDefaultInstance().getBfdTag();
        onChanged();
        return this;
      }
      void setBfdTag(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        bfdTag_ = value;
        onChanged();
      }
      
      // repeated string bfd_cat_vec = 7;
      private com.google.protobuf.LazyStringList bfdCatVec_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBfdCatVecIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          bfdCatVec_ = new com.google.protobuf.LazyStringArrayList(bfdCatVec_);
          bitField0_ |= 0x00000040;
         }
      }
      public java.util.List<String>
          getBfdCatVecList() {
        return java.util.Collections.unmodifiableList(bfdCatVec_);
      }
      public int getBfdCatVecCount() {
        return bfdCatVec_.size();
      }
      public String getBfdCatVec(int index) {
        return bfdCatVec_.get(index);
      }
      public Builder setBfdCatVec(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBfdCatVecIsMutable();
        bfdCatVec_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addBfdCatVec(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBfdCatVecIsMutable();
        bfdCatVec_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllBfdCatVec(
          java.lang.Iterable<String> values) {
        ensureBfdCatVecIsMutable();
        super.addAll(values, bfdCatVec_);
        onChanged();
        return this;
      }
      public Builder clearBfdCatVec() {
        bfdCatVec_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      void addBfdCatVec(com.google.protobuf.ByteString value) {
        ensureBfdCatVecIsMutable();
        bfdCatVec_.add(value);
        onChanged();
      }
      
      // repeated string bfd_tag_vec = 8;
      private com.google.protobuf.LazyStringList bfdTagVec_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBfdTagVecIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          bfdTagVec_ = new com.google.protobuf.LazyStringArrayList(bfdTagVec_);
          bitField0_ |= 0x00000080;
         }
      }
      public java.util.List<String>
          getBfdTagVecList() {
        return java.util.Collections.unmodifiableList(bfdTagVec_);
      }
      public int getBfdTagVecCount() {
        return bfdTagVec_.size();
      }
      public String getBfdTagVec(int index) {
        return bfdTagVec_.get(index);
      }
      public Builder setBfdTagVec(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBfdTagVecIsMutable();
        bfdTagVec_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addBfdTagVec(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBfdTagVecIsMutable();
        bfdTagVec_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllBfdTagVec(
          java.lang.Iterable<String> values) {
        ensureBfdTagVecIsMutable();
        super.addAll(values, bfdTagVec_);
        onChanged();
        return this;
      }
      public Builder clearBfdTagVec() {
        bfdTagVec_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      void addBfdTagVec(com.google.protobuf.ByteString value) {
        ensureBfdTagVecIsMutable();
        bfdTagVec_.add(value);
        onChanged();
      }
      
      // optional string loc = 9;
      private java.lang.Object loc_ = "";
      public boolean hasLoc() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getLoc() {
        java.lang.Object ref = loc_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          loc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLoc(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        loc_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoc() {
        bitField0_ = (bitField0_ & ~0x00000100);
        loc_ = getDefaultInstance().getLoc();
        onChanged();
        return this;
      }
      void setLoc(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        loc_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:bfd.newsprofile.NewsProfile)
    }
    
    static {
      defaultInstance = new NewsProfile(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:bfd.newsprofile.NewsProfile)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bfd_newsprofile_NewsProfile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bfd_newsprofile_NewsProfile_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021newsprofile.proto\022\017bfd.newsprofile\"\235\001\n" +
      "\013NewsProfile\022\013\n\003cid\030\001 \002(\t\022\013\n\003iid\030\002 \002(\t\022\013" +
      "\n\003url\030\003 \002(\t\022\016\n\006bfdiid\030\004 \002(\t\022\017\n\007bfd_cat\030\005" +
      " \001(\t\022\017\n\007bfd_tag\030\006 \001(\t\022\023\n\013bfd_cat_vec\030\007 \003" +
      "(\t\022\023\n\013bfd_tag_vec\030\010 \003(\t\022\013\n\003loc\030\t \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bfd_newsprofile_NewsProfile_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bfd_newsprofile_NewsProfile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bfd_newsprofile_NewsProfile_descriptor,
              new java.lang.String[] { "Cid", "Iid", "Url", "Bfdiid", "BfdCat", "BfdTag", "BfdCatVec", "BfdTagVec", "Loc", },
              bfd.newsprofile.Newsprofile.NewsProfile.class,
              bfd.newsprofile.Newsprofile.NewsProfile.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
